version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run start:dev

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./web-client:/app
      - /app/node_modules
    depends_on:
      - server

  # Chrome extension development (if needed)
  # Note: Chrome extensions typically don't need a container
  # but you can add one for testing if required
